name: Update documentation

on:
  push:
  workflow_dispatch:

jobs:
  update_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Update docs
        run: node .github/actions/documentation.js

      - name: Commit files
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated documentation"
          git push
